### ISSUE TITLE
"server" in below code is not pre-defined before.

### ISSUE THREAD

**Issue by LLNeal** [RedouaneTaoussi/DoIPScan#1]
_The key word "server" is not predefined in doipScan.py file, should be scan.Scan?_
        scan = **server**.Scan(ecu_ip_address,ecu_logical_address)
        scan = **server**.Scan(ecu_ip_address,ecu_logical_address,client_logical_address)
@R4d0y

**Comment by LLNeal** [comment]
> ```
>     scan = **server**.Scan(ecu_ip_address,ecu_logical_address)
>     scan = **server**.Scan(ecu_ip_address,ecu_logical_address,client_logical_address)
> ```

**Comment by R4d0y** [comment]
Yes, thank you for pointing it out.
